// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Weather

#ifndef _WEATHER_UI_H
#define _WEATHER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_cityText;
extern lv_obj_t * ui_weatherIcon;
extern lv_obj_t * ui_currentTemp;
extern lv_obj_t * ui_updateTime;
extern lv_obj_t * ui_highLowTemp;
extern lv_obj_t * ui_weatherText;
extern lv_obj_t * ui_humidityIcon;
extern lv_obj_t * ui_windIcon;
extern lv_obj_t * ui_rainIcon;
extern lv_obj_t * ui_uvIcon;
extern lv_obj_t * ui_humidityText;
extern lv_obj_t * ui_uvText;
extern lv_obj_t * ui_rainText;
extern lv_obj_t * ui_windText;
extern lv_obj_t * ui_countryText;
extern lv_obj_t * ui_wifiName;
extern lv_obj_t * ui_forecastList;
extern lv_obj_t * ui_forecastItem;
extern lv_obj_t * ui_forecastIcon;
extern lv_obj_t * ui_forecastTemp;
extern lv_obj_t * ui_forecastTime;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_day_176_png);    // assets/day_176.png
LV_IMG_DECLARE(ui_img_humidity_icon_png);    // assets/humidity_icon.png
LV_IMG_DECLARE(ui_img_wind_icon_png);    // assets/wind_icon.png
LV_IMG_DECLARE(ui_img_rain_icon_png);    // assets/rain_icon.png
LV_IMG_DECLARE(ui_img_uv_icon_png);    // assets/uv_icon.png
LV_IMG_DECLARE(ui_img_day_368_png);    // assets/day_368.png
LV_IMG_DECLARE(ui_img_day_113_png);    // assets/day_113.png
LV_IMG_DECLARE(ui_img_day_116_png);    // assets/day_116.png
LV_IMG_DECLARE(ui_img_day_119_png);    // assets/day_119.png
LV_IMG_DECLARE(ui_img_day_122_png);    // assets/day_122.png
LV_IMG_DECLARE(ui_img_day_143_png);    // assets/day_143.png
LV_IMG_DECLARE(ui_img_day_179_png);    // assets/day_179.png
LV_IMG_DECLARE(ui_img_day_182_png);    // assets/day_182.png
LV_IMG_DECLARE(ui_img_day_185_png);    // assets/day_185.png
LV_IMG_DECLARE(ui_img_day_200_png);    // assets/day_200.png
LV_IMG_DECLARE(ui_img_day_227_png);    // assets/day_227.png
LV_IMG_DECLARE(ui_img_day_230_png);    // assets/day_230.png
LV_IMG_DECLARE(ui_img_day_248_png);    // assets/day_248.png
LV_IMG_DECLARE(ui_img_day_260_png);    // assets/day_260.png
LV_IMG_DECLARE(ui_img_day_263_png);    // assets/day_263.png
LV_IMG_DECLARE(ui_img_day_266_png);    // assets/day_266.png
LV_IMG_DECLARE(ui_img_day_281_png);    // assets/day_281.png
LV_IMG_DECLARE(ui_img_day_284_png);    // assets/day_284.png
LV_IMG_DECLARE(ui_img_day_293_png);    // assets/day_293.png
LV_IMG_DECLARE(ui_img_day_296_png);    // assets/day_296.png
LV_IMG_DECLARE(ui_img_day_299_png);    // assets/day_299.png
LV_IMG_DECLARE(ui_img_day_302_png);    // assets/day_302.png
LV_IMG_DECLARE(ui_img_day_305_png);    // assets/day_305.png
LV_IMG_DECLARE(ui_img_day_308_png);    // assets/day_308.png
LV_IMG_DECLARE(ui_img_day_311_png);    // assets/day_311.png
LV_IMG_DECLARE(ui_img_day_314_png);    // assets/day_314.png
LV_IMG_DECLARE(ui_img_day_317_png);    // assets/day_317.png
LV_IMG_DECLARE(ui_img_day_320_png);    // assets/day_320.png
LV_IMG_DECLARE(ui_img_day_323_png);    // assets/day_323.png
LV_IMG_DECLARE(ui_img_day_326_png);    // assets/day_326.png
LV_IMG_DECLARE(ui_img_day_329_png);    // assets/day_329.png
LV_IMG_DECLARE(ui_img_day_332_png);    // assets/day_332.png
LV_IMG_DECLARE(ui_img_day_335_png);    // assets/day_335.png
LV_IMG_DECLARE(ui_img_day_338_png);    // assets/day_338.png
LV_IMG_DECLARE(ui_img_day_350_png);    // assets/day_350.png
LV_IMG_DECLARE(ui_img_day_353_png);    // assets/day_353.png
LV_IMG_DECLARE(ui_img_day_356_png);    // assets/day_356.png
LV_IMG_DECLARE(ui_img_day_359_png);    // assets/day_359.png
LV_IMG_DECLARE(ui_img_day_362_png);    // assets/day_362.png
LV_IMG_DECLARE(ui_img_day_365_png);    // assets/day_365.png
LV_IMG_DECLARE(ui_img_day_371_png);    // assets/day_371.png
LV_IMG_DECLARE(ui_img_day_374_png);    // assets/day_374.png
LV_IMG_DECLARE(ui_img_day_377_png);    // assets/day_377.png
LV_IMG_DECLARE(ui_img_day_386_png);    // assets/day_386.png
LV_IMG_DECLARE(ui_img_day_389_png);    // assets/day_389.png
LV_IMG_DECLARE(ui_img_day_392_png);    // assets/day_392.png
LV_IMG_DECLARE(ui_img_day_395_png);    // assets/day_395.png
LV_IMG_DECLARE(ui_img_night_113_png);    // assets/night_113.png
LV_IMG_DECLARE(ui_img_night_116_png);    // assets/night_116.png
LV_IMG_DECLARE(ui_img_night_119_png);    // assets/night_119.png
LV_IMG_DECLARE(ui_img_night_122_png);    // assets/night_122.png
LV_IMG_DECLARE(ui_img_night_143_png);    // assets/night_143.png
LV_IMG_DECLARE(ui_img_night_176_png);    // assets/night_176.png
LV_IMG_DECLARE(ui_img_night_179_png);    // assets/night_179.png
LV_IMG_DECLARE(ui_img_night_182_png);    // assets/night_182.png
LV_IMG_DECLARE(ui_img_night_185_png);    // assets/night_185.png
LV_IMG_DECLARE(ui_img_night_200_png);    // assets/night_200.png
LV_IMG_DECLARE(ui_img_night_227_png);    // assets/night_227.png
LV_IMG_DECLARE(ui_img_night_230_png);    // assets/night_230.png
LV_IMG_DECLARE(ui_img_night_248_png);    // assets/night_248.png
LV_IMG_DECLARE(ui_img_night_260_png);    // assets/night_260.png
LV_IMG_DECLARE(ui_img_night_263_png);    // assets/night_263.png
LV_IMG_DECLARE(ui_img_night_266_png);    // assets/night_266.png
LV_IMG_DECLARE(ui_img_night_281_png);    // assets/night_281.png
LV_IMG_DECLARE(ui_img_night_284_png);    // assets/night_284.png
LV_IMG_DECLARE(ui_img_night_293_png);    // assets/night_293.png
LV_IMG_DECLARE(ui_img_night_296_png);    // assets/night_296.png
LV_IMG_DECLARE(ui_img_night_299_png);    // assets/night_299.png
LV_IMG_DECLARE(ui_img_night_302_png);    // assets/night_302.png
LV_IMG_DECLARE(ui_img_night_305_png);    // assets/night_305.png
LV_IMG_DECLARE(ui_img_night_308_png);    // assets/night_308.png
LV_IMG_DECLARE(ui_img_night_311_png);    // assets/night_311.png
LV_IMG_DECLARE(ui_img_night_314_png);    // assets/night_314.png
LV_IMG_DECLARE(ui_img_night_317_png);    // assets/night_317.png
LV_IMG_DECLARE(ui_img_night_320_png);    // assets/night_320.png
LV_IMG_DECLARE(ui_img_night_323_png);    // assets/night_323.png
LV_IMG_DECLARE(ui_img_night_326_png);    // assets/night_326.png
LV_IMG_DECLARE(ui_img_night_329_png);    // assets/night_329.png
LV_IMG_DECLARE(ui_img_night_332_png);    // assets/night_332.png
LV_IMG_DECLARE(ui_img_night_335_png);    // assets/night_335.png
LV_IMG_DECLARE(ui_img_night_338_png);    // assets/night_338.png
LV_IMG_DECLARE(ui_img_night_350_png);    // assets/night_350.png
LV_IMG_DECLARE(ui_img_night_353_png);    // assets/night_353.png
LV_IMG_DECLARE(ui_img_night_356_png);    // assets/night_356.png
LV_IMG_DECLARE(ui_img_night_359_png);    // assets/night_359.png
LV_IMG_DECLARE(ui_img_night_362_png);    // assets/night_362.png
LV_IMG_DECLARE(ui_img_night_365_png);    // assets/night_365.png
LV_IMG_DECLARE(ui_img_night_368_png);    // assets/night_368.png
LV_IMG_DECLARE(ui_img_night_371_png);    // assets/night_371.png
LV_IMG_DECLARE(ui_img_night_374_png);    // assets/night_374.png
LV_IMG_DECLARE(ui_img_night_377_png);    // assets/night_377.png
LV_IMG_DECLARE(ui_img_night_386_png);    // assets/night_386.png
LV_IMG_DECLARE(ui_img_night_389_png);    // assets/night_389.png
LV_IMG_DECLARE(ui_img_night_392_png);    // assets/night_392.png
LV_IMG_DECLARE(ui_img_night_395_png);    // assets/night_395.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
